### ISSUE TITLE
Android 13 issue

### ISSUE THREAD

**Issue by ibrahimhaydarids** [MajidArabi/AndroidFilePicker#5]
file not loaded on android 13 devices

**Comment by MajidArabi** [comment]
Thank you for reporting the problem.
I will check it out soon.

**Comment by nguyencongbinh** [comment]
Hello,
Please support android 13

**Comment by MajidArabi** [comment]
Hi @nguyencongbinh and @ibrahimhaydarids.
I checked it and everything works fine on Android 13.
Tested device: Xiaomi 12T with Android 13.
Can you tell me what device you tested on?

**Comment by integrateddigitalsystems** [comment]
it could works on Android 13 if targetSDKVersion in gradle file is below 33 , when trying to update targetSDKVersion to 33 then the library tries to open bottomsheet gallery and failed
