### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by HadyAlkahlout** [MajidArabi/AndroidFilePicker#9]
> Could not find com.github.majidarabi:AndroidFilePicker:0.2.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/majidarabi/AndroidFilePicker/0.2.1/AndroidFilePicker-0.2.1.pom
       - https://repo.maven.apache.org/maven2/com/github/majidarabi/AndroidFilePicker/0.2.1/AndroidFilePicker-0.2.1.pom
       - https://jitpack.io/com/github/majidarabi/AndroidFilePicker/0.2.1/AndroidFilePicker-0.2.1.pom
     Required by:
         project :app

**Comment by MajidArabi** [comment]
hi @HadyAlkahlout .
You must add this line in build.gradle
` implementation("com.github.MajidArabi:AndroidFilePicker:0.2.2")`
